server:
#  context-path: /userDTO
    port: 8086
spring:
    application:
        name: BootMongo
    data:
        mongodb:
            database: signup
            host: localhost
            port: 27017
    rabbitmq:
            host: localhost
            port: 5672
jsd:
  rabbitmq:
    queue: jsd.queuereg
    exchange: jsd.directreg
    routingkey: jsd.routingkeyreg