server:
    ports:
        http: 8087
    port: 8086
    ssl:
        key-store: keystore.p12
        key-store-password: root123
        keyStoreType: PKCS12
        keyAlias: tomcat

security:
    require-ssl: true


spring:
    application:
        name: BootMongo
    data:
        mongodb:
            database: signup
            host: localhost
            port: 27017
    rabbitmq:
        host: localhost
        port: 5672
jsh:
    rabbitmq:
        queue: jsh.queuereg
        exchange: jsh.directreg
        routingkey: jsh.routingkeyreg
jsf:
    rabbitmq:
        queue: jsf.queuereg
        exchange: jsf.directreg
        routingkey: jsf.routingkeyreg