server:
  port: 8010
spring:
  rabbitmq:
    host: localhost
    port: 5672
jsd:
  rabbitmq:
    queue: jsd.queue1
    exchange: jsd.direct1
    routingkey: jsd.routingkey1
jst:
  rabbitmq:
    queue: jst.queue1
    exchange: jst.direct1
    routingkey: jst.routingkey1
