language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2/repository"
addons:
  sonarcloud:
    organization: "stackroute" # the key of the org you chose at step #3
    token:
      secure: 5b6bbe21331c4f71f29d79e9a674902746d98ca9
script:
  mvn sonar:sonar -Dsonar.projectKey=stackroute_boeing-wave4-eroteme -Dsonar.organization=stackroute -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3ffb4c27b1606f2e768ce08120eacfc3fdd5c3e7
after_success:
  - bash <(curl -s https://codecov.io/bash)
