server:
  context-path: /nlp
  port: 8070
  rabbitmq:
    host: localhost
    port: 5672
jsb:
  rabbitmq:
    queue: jsb.queue
    exchange: jsb.direct
    routingkey: jsb.routingkey

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8093/eureka

spring:
  application:
    name: nlp-service