spring:
  data:
    mongodb:
      database: myprofile_db
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
server:
  port: 8099
#Recommendation command Service
jfa:
  rabbitmq:
    queue: jfa.queue2
    exchange: jfa.direct2
    routingkey: jfa.routingkey2
#User-Profile Service
jfb:
  rabbitmq:
    queue: jfb.queue2
    exchange: jfb.direct2
    routingkey: jfb.routingkey2
#Question and Answer Service
jfc:
  rabbitmq:
    queue: jfc.queue2
    exchange: jfc.direct2
    routingkey: jfc.routingkey2
#Login Service
jfd:
  rabbitmq:
    queue: jfd.queue2
    exchange: jfd.direct2
    routingkey: jfd.routingkey2
#Search Service
jfe:
  rabbitmq:
    queue: jfe.queue2
    exchange: jfe.direct2
    routingkey: jfe.routingkey2
