server:
  context-path: /question
  ports:
    http: 8088
  port: 8090
  ssl:
    key-store: keystore.p12
    key-store-password: root123
    keyStoreType: PKCS12
    keyAlias: tomcat

security:
  require-ssl: true


spring:
  application:
    name: BootMongo
  data:
    mongodb:
      database: ques_db
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
jsa:
  rabbitmq:
    queue: jsa.queue1
    exchange: jsa.direct1
    routingkey: jsa.routingkey1
jsd:
  rabbitmq:
    queue: jsd.queue1
    exchange: jsd.direct1
    routingkey: jsd.routingkey1
jse:
  rabbitmq:
    queue: jse.queue1
    exchange: jse.direct1
    routingkey: jse.routingkey1
jsf:
  rabbitmq:
    queue: jsf.queue1
    exchange: jsf.direct1
    routingkey: jsf.routingkey1