server:
  port: 8099
#  ports:
#    http: 8094
#  port: 8099
#  ssl:
#    key-store: keystore.p12
#    key-store-password: root123
#    keyStoreType: PKCS12
#    keyAlias: tomcat

security:
  require-ssl: true

spring:
  application:
    name: BootMongo
  data:
    mongodb:
      database: topic
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
jsa:
  rabbitmq:
    queue: jsa.queue1
    exchange: jsa.direct1
    routingkey: jsa.routingkey1
jsb:
  rabbitmq:
    queue: jsb.queue
    exchange: jsb.direct
    routingkey: jsb.routingkey


