server:
  port: 8099


security:
  require-ssl: true

spring:
  application:
    name: BootMongo
  data:
    mongodb:
      database: topic
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
jsa:
  rabbitmq:
    queue: jsa.queue1
    exchange: jsa.direct1
    routingkey: jsa.routingkey1
jsb:
  rabbitmq:
    queue: jsb.queue
    exchange: jsb.direct
    routingkey: jsb.routingkey


